read from file

diff --git a/root/etc/cont-init.d/30-cloudflare-setup b/root/etc/cont-init.d/30-cloudflare-setup
--- a/root/etc/cont-init.d/30-cloudflare-setup
+++ b/root/etc/cont-init.d/30-cloudflare-setup
@@ -3,10 +3,10 @@
 . /app/cloudflare.sh
 
 # Load ZONE and SUBDOMAIN vars from Docker Swarm secrets, if available:
-if [ -f "$SUBDOMAIN_FILE" ]; then
-    SUBDOMAIN=$(cat $SUBDOMAIN_FILE)
-    echo $SUBDOMAIN
-fi
+# if [ -f "$SUBDOMAIN_FILE" ]; then
+#     SUBDOMAIN=$(cat $SUBDOMAIN_FILE)
+#     echo $SUBDOMAIN
+# fi
 if [ -f "$ZONE_FILE" ]; then
     ZONE=$(cat $ZONE_FILE)
 fi
@@ -77,24 +77,52 @@ if [ "$PublicIpAddress" == "" ]; then
   exit 1
 fi
 
-# Get the ID of the dns record from the CloudFlare API
-CFDnsRecordName=$(getDnsRecordName)
-CFDnsRecordId=$(getDnsRecordId $CFZoneId $CFDnsRecordName)
 
-# If the dns record does not exist, create it now.
-if [ "$CFDnsRecordId" == "null" ]; then
-  echo "DNS record for '$CFDnsRecordName' was not found in $ZONE zone. Creating now..."
-  CFDnsRecordId=$(createDnsRecord $CFZoneId $CFDnsRecordName $PublicIpAddress)
+if [ -f "$SUBDOMAIN_FILE" ]; then
 
-  if [ "$CFDnsRecordId" == "null" ]; then
-    echo "----------------------------------------------------------------"
-    echo "ERROR: Failed to create DNS record '$CFDnsRecordName'"
-    echo "----------------------------------------------------------------"
-    exit 1
-  fi
+  while read -r line; do
+    # Get the ID of the dns record from the CloudFlare API
+    CFDnsRecordName=$(getDnsRecordName($line))
+    CFDnsRecordId=$(getDnsRecordId $CFZoneId $CFDnsRecordName)
 
+    # If the dns record does not exist, create it now.
+    if [ "$CFDnsRecordId" == "null" ]; then
+      echo "DNS record for '$CFDnsRecordName' was not found in $ZONE zone. Creating now..."
+      CFDnsRecordId=$(createDnsRecord $CFZoneId $CFDnsRecordName $PublicIpAddress)
+
+      if [ "$CFDnsRecordId" == "null" ]; then
+        echo "----------------------------------------------------------------"
+        echo "ERROR: Failed to create DNS record '$CFDnsRecordName'"
+        echo "----------------------------------------------------------------"
+        exit 1
+      fi
+
+    fi
+
+    echo "DNS Record: $CFDnsRecordName ($CFDnsRecordId)"
+    echo "CF_ZONE_ID=\"$CFZoneId\" CF_RECORD_ID=\"$CFDnsRecordId\" CF_RECORD_NAME=\"$CFDnsRecordName\"" > /config/cloudflare.conf
+    echo "$CRON	/etc/cont-init.d/50-ddns" > /var/spool/cron/crontabs/root
+  done <$SUBDOMAIN_FILE
+else 
+    # Get the ID of the dns record from the CloudFlare API
+    CFDnsRecordName=$(getDnsRecordName($SUBDOMAIN))
+    CFDnsRecordId=$(getDnsRecordId $CFZoneId $CFDnsRecordName)
+
+    # If the dns record does not exist, create it now.
+    if [ "$CFDnsRecordId" == "null" ]; then
+      echo "DNS record for '$CFDnsRecordName' was not found in $ZONE zone. Creating now..."
+      CFDnsRecordId=$(createDnsRecord $CFZoneId $CFDnsRecordName $PublicIpAddress)
+
+      if [ "$CFDnsRecordId" == "null" ]; then
+        echo "----------------------------------------------------------------"
+        echo "ERROR: Failed to create DNS record '$CFDnsRecordName'"
+        echo "----------------------------------------------------------------"
+        exit 1
+      fi
+
+    fi
+
+    echo "DNS Record: $CFDnsRecordName ($CFDnsRecordId)"
+    echo "CF_ZONE_ID=\"$CFZoneId\" CF_RECORD_ID=\"$CFDnsRecordId\" CF_RECORD_NAME=\"$CFDnsRecordName\"" > /config/cloudflare.conf
+    echo "$CRON	/etc/cont-init.d/50-ddns" > /var/spool/cron/crontabs/root
 fi
-
-echo "DNS Record: $CFDnsRecordName ($CFDnsRecordId)"
-echo "CF_ZONE_ID=\"$CFZoneId\" CF_RECORD_ID=\"$CFDnsRecordId\" CF_RECORD_NAME=\"$CFDnsRecordName\"" > /config/cloudflare.conf
-echo "$CRON	/etc/cont-init.d/50-ddns" > /var/spool/cron/crontabs/root
